<?php
session_start();
require_once('../config.php');
$_SESSION=array();
if(isset($_COOKIE[session_name()])==true)
{
    setcookie(session_name(),'',time()-42000,'/');
}
session_destroy();
set_flash('danger','ログアウトしました');
header('Location:staff_top.php');
?>